config/routes.rb
Rails.application.routes.draw do
  root "reviews#index"

  resources :reviews

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/review.rb
class Review < ApplicationRecord
  validates :report_title, :student_name, presence: true
  # enum :report_title, [:github, :linkedin, :resume, :cover_page, :portfolio]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  include Pagy::Backend
  def index
    @pagy, @reviews = pagy(Review.all, items: 10)
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)

    if @review.save
      redirect_to @review
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])

    if @review.update(review_params)
      redirect_to @review
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    redirect_to root_path, status: :see_other
  end


  private
    def review_params
      params.require(:review).permit(:report_title, :bio, :profile_image, :pinned_repositories, :student_name, :contributions, :repository_list )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

end

app/helpers/reviews_helper.rb
module ReviewsHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentFeedback</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_with model: review do |form| %>

  <div class='title-form'>
Review Type: <%= selected_title = form.select :report_title,
      {
        "Form Type" => [ ["Resume"], ["LinkedIn"], ["Portfolio"], ["Cover Page"], ["Github"] ]
      } %>
  <div><br>


  <div >
    <%=form.label :student_name%><br>
    <%= form.text_field :student_name%>
      <%review.errors.full_messages_for(:student_name).each do |message|%>
    <div><%= message %></div>
    <% end %>
  </div><br>


  <div class='title-form'>
    Bio: <%= category1 = form.select :bio,
      {
        "Form Type" => [ ["1 - Lacking or too generic", "1"], ["2 - Specifies role but no tech listed", "2"], ["3 - Specifies role and lists some tech", "3"], ["4 - Specific role and tech listed; mirrors LinkedIn profile", "4"], ["5 - Precise and detailed, fuly mirrors LinkedIn profile", "5"]  ]
      },
      selected: "RS" %>
  <div><br>

  <div class='title-form'>
    Profile Image: <%= category2 = form.select :profile_image,
      {
        "Form Type" => [ ["1 - Lacking or too generic", "1"], ["2 - Specifies role but no tech listed", "2"], ["3 - Specifies role and lists some tech", "3"], ["4 - Specific role and tech listed; mirrors LinkedIn profile", "4"], ["5 - Precise and detailed, fuly mirrors LinkedIn profile", "5"]  ]
      },
      selected: "RS" %>
  <div><br>

  <div class='title-form'>
    Pinned Repositories: <%= category2 = form.select :pinned_repositories,
      {
        "Form Type" => [ ["1 - Lacking or too generic", "1"], ["2 - Specifies role but no tech listed", "2"], ["3 - Specifies role and lists some tech", "3"], ["4 - Specific role and tech listed; mirrors LinkedIn profile", "4"], ["5 - Precise and detailed, fuly mirrors LinkedIn profile", "5"]  ]
      },
      selected: "RS" %>
  <div><br>

  <div class='title-form'>
    Contributions: <%= category2 = form.select :contributions,
      {
        "Form Type" => [ ["1 - Lacking or too generic", "1"], ["2 - Specifies role but no tech listed", "2"], ["3 - Specifies role and lists some tech", "3"], ["4 - Specific role and tech listed; mirrors LinkedIn profile", "4"], ["5 - Precise and detailed, fuly mirrors LinkedIn profile", "5"]  ]
      },
      selected: "RS" %>
  <div><br>

  <div class='title-form'>
    Repository List: <%= category2 = form.select :repository_list,
      {
        "Form Type" => [ ["1 - Lacking or too generic", "1"], ["2 - Specifies role but no tech listed", "2"], ["3 - Specifies role and lists some tech", "3"], ["4 - Specific role and tech listed; mirrors LinkedIn profile", "4"], ["5 - Precise and detailed, fuly mirrors LinkedIn profile", "5"]  ]
      },
      selected: "RS" %>
  <div><br>

  <div>
    <%=form.submit%>
  </div>


<% end %>
    <%= button_to "Cancel", root_path, method: :get %>

app/views/reviews/_pagy_nav.html.erb
<% pagy = locals[:pagy] %>
<% reviews = locals[:reviews] %>

<%= raw pagy_nav(pagy) %>

app/views/reviews/_resumeform.html.erb
<%= form_with model: review do |form| %>
  <div>
    <%=form.label :cat_name%><br>
    <%= form.text_field :student_name%>
      <%review.errors.full_messages_for(:student_name).each do |message|%>
    <div><%= message %></div>
    <% end %>
  </div><br>

<%end%>

app/views/reviews/_review_table.html.erb
<%= tag.tr id: dom_id(review) do %>
  <td><%= review.report_title %></td>
  <td><%= review.category %></td>
  <td><%= number_to_currency product.price %></td>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render "form", review: @review%>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<div class="table-container">
  <table>
    <thead>
      <tr>
        <th>Student Name</th>
        <th>Review Category</th>
        <th>Cohort</th>
        <th>Date</th>
      </tr>
    </thead>
    <% @reviews.each do |review| %>
      <tbody>
      <tr>
        <td>
          <%= link_to review.student_name, review %>
        </td><td>
          <%= link_to review.report_title, review %>
        </td>
      </tr>
      </tbody>
    <% end %>

  </table>
</div>

<%= button_to "New Review", new_review_path, method: :get %>
<%== pagy_nav(@pagy) if @pagy.pages > 1 %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render "form", review: @review %>

app/views/reviews/show.html.erb
<h1><%= @review.report_title%> </h1>
<div class='show-body'>
  <ul>
    <li><p>Student Name: <%= @review.student_name%> </p></li>
    <li><p>Bio Category: <%= @review.bio%> </p></li>
  </ul>
<div>

<%= button_to "Edit", edit_review_path(@review), method: :get%>
<%= button_to "Delete", review_path(@review), method: :delete, data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
    } %>
<%= button_to "Home", root_path, method: :get %>